const vehicles = [
  {
    id: 1,
    name: "Toyota Camry",
    maker: "Toyota",
    model: 2018,
    petrol_consumption: 30,
    price: 250,
    miles: 50000,
    imageUrl: "img/camry.webp",
  },
  {
    id: 2,
    name: "Honda Accord",
    maker: "Honda",
    model: 2009,
    petrol_consumption: 25,
    price: 270,
    miles: 45000,
    imageUrl: "img/Accord.jpg",
  },
  {
    id: 3,
    name: "Ford Mustang",
    maker: "Ford",
    model: 2015,
    petrol_consumption: 20,
    price: 350,
    miles: 40000,
    imageUrl: "img/mustang.jpeg",
  },
  {
    id: 4,
    name: "Chevrolet Silverado",
    maker: "Chevrolet",
    model: 2012,
    petrol_consumption: 18,
    price: 400,
    miles: 60000,
    imageUrl: "img/silverado",
  },
  {
    id: 5,
    name: "BMW 3 Series",
    maker: "BMW",
    model: 2020,
    petrol_consumption: 28,
    price: 400,
    miles: 35000,
    imageUrl: "img/3series",
  },
  {
    id: 6,
    name: "Rolls Royce Ghost",
    maker: "Rolls Royce",
    model: 2023,
    petrol_consumption: 16,
    price: 700,
    miles: 3000,
    imageUrl: "img/",
  },
  {
    id: 7,
    name: "Mercedes-Benz C-Class",
    maker: "Mercedes-Benz",
    model: 2008,
    petrol_consumption: 26,
    price: 450,
    miles: 30000,
    imageUrl: "img/",
  },
  {
    id: 8,
    name: "Audi A4",
    maker: "Audi",
    model: 2017,
    petrol_consumption: 24,
    price: 420,
    miles: 32000,
    imageUrl: "img/",
  },
  {
    id: 9,
    name: "Nissan Altima",
    maker: "Nissan",
    model: 2005,
    petrol_consumption: 27,
    price: 280,
    miles: 48000,
    imageUrl: "img/",
  },
  {
    id: 10,
    name: "Volkswagen Jetta",
    maker: "Volkswagen",
    model: 2011,
    petrol_consumption: 29,
    price: 300,
    miles: 40000,
    imageUrl: "img/",
  },
  {
    id: 11,
    name: "Subaru Outback",
    maker: "Subaru",
    model: 2014,
    petrol_consumption: 26,
    price: 320,
    miles: 35000,
    imageUrl: "img/",
  },
];

export default { vehicles };
